make:
	g++ -std=c++11 -Ofast main.cpp Predictor.cpp structures/SimilarityList.cpp structures/ItemList.cpp FileManager.cpp -o recommender
	g++ -std=c++11 -Ofast main.cpp Predictor.cpp structures/SimilarityList.cpp structures/ItemList.cpp FileManager.cpp -o run
